# COSS Metadata Template v0.0.2
# This is the official COSS (Contriboss Open Source Standard) specification template
# Copy this file to your project root as coss.toml and customize for your project

##########################################################
# 1. Basic Project Information
name = "ragdoll-rails"
version = "0.1.5"
description = "Rails Engine for Multi-modal Retrieval Augmented Generation (RAG)"
licenses = ["MIT"]
ai_contributions = true  # AI was used to enhance testing framework
coss_compliant = true
homepage = "https://github.com/MadBomber/ragdoll-rails"
keywords = ["ruby", "rails", "engine", "ragdoll", "rag", "multi-modal", "ai"]

##########################################################
# 2. Repository and Issue Tracking
repository = "https://github.com/MadBomber/ragdoll-rails"
issue_tracker = "https://github.com/MadBomber/ragdoll-rails/issues"
documentation = "https://github.com/MadBomber/ragdoll-rails/blob/main/README.md"
security_policy = ""

##########################################################
# 3. Languages, Frameworks, and Platforms
languages = ["ruby"]

[frameworks]
# Pure Ruby library - no specific framework dependencies

supported_platforms = ["linux", "darwin", "windows"]

##########################################################
# 4. Dependency Lock Files
[dependency_locks]
ruby = "Gemfile.lock"

[packaging]
ruby = "gem build ragdoll-rails.gemspec"

##########################################################
# 5. Maintainers and Governance
maintainers = ["dvanhoozer@gmail.com"]
governance = { type = "informal" }

##########################################################
# 6. Linting, Formatting, and Static Analysis
lint = "bundle exec rubocop"
format = "bundle exec rubocop -a"
static_analysis = ["bundle exec rubocop"]

##########################################################
# 7. CI and Build Commands
build = "bundle install"
test = "rake test"
coverage = ""

##########################################################
# 8. Tests and Quality Metrics
[test_frameworks]
ruby = "minitest"

test_report_format = "minitest"
coverage_threshold = 0

##########################################################
# 9. Commit Guidelines and Formats
commit_message_format = ""

##########################################################
# 10. Release and Changelog
changelog = "CHANGELOG.md"
release_tag_pattern = "v{version}"

##########################################################
# 11. Badges and Integrations (Optional)
[badges]
ci = "https://github.com/MadBomber/ragdoll-rails/actions/workflows/ruby.yml/badge.svg"
coverage = ""
license_badge = ""

##########################################################
# 12. Optional Miscellaneous Fields
chat = ""
support = { type = "github", contact = "https://github.com/MadBomber/ragdoll-rails/issues" }
apidocs = ""

##########################################################
# 13. Environment and Runtime Info
[environments]
ruby = "3.0+"

##########################################################
# 14. Data Schemas and Contracts
[data_contracts]
openapi = ""
graphql = ""
avro = ""

##########################################################
# 15. Project Classification
project_type = "library"
maturity = "stable"
audience = ["developers", "ruby-developers"]

##########################################################
# 16. Localization / Internationalization
[i18n]
default_locale = "en"
supported_locales = ["en"]
translation_files = ""

##########################################################
# 17. Contribution Automation
[contribution_tooling]
dependabot = false
precommit_hooks = false
ai_review = "disabled"
codeowners = ""

##########################################################
# 18. Security Scanning and SBOM
[security]
sbom = ""
vulnerability_scanner = ""
license_compliance_tool = ""

##########################################################
# 19. Documentation Quality Flags
[docs]
coverage = 0
style = ""
ai_summary_enabled = false

##########################################################
# 20. Submodules and Component References
[submodules]
# References to integration gems in the ragdoll ecosystem
ragdoll          = "https://github.com/MadBomber/ragdoll"
ragdoll-cli      = "https://github.com/MadBomber/ragdoll-cli"
ragdoll-rails    = "https://github.com/MadBomber/ragdoll-rails"
ragdoll-docs     = "https://github.com/MadBomber/ragdoll-docs"
ragdoll_demo_app = "https://github.com/MadBomber/ragdoll_demo_app"
ragdoll_test_app = "https://github.com/MadBomber/ragdoll_test_app"
