# This file contains the database configuration for the Ragdoll gem, using environment variables.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAGDOLL_POOL", 5) %>
  timeout: <%= ENV.fetch("RAGDOLL_TIMEOUT", 5000) %>

development:
  <<: *default
  host: <%= ENV.fetch("RAGDOLL_HOST", "localhost") %>
  database: <%= ENV.fetch("RAGDOLL_DATABASE", "ragdoll_development") %>
  username: <%= ENV.fetch("RAGDOLL_USER", "user") %>
  password: <%= ENV.fetch("RAGDOLL_PASSWORD", "password") %>

test:
  <<: *default
  host: <%= ENV.fetch("RAGDOLL_HOST", "localhost") %>
  database: <%= ENV.fetch("RAGDOLL_DATABASE", "ragdoll_test") %>
  username: <%= ENV.fetch("RAGDOLL_USER", "user") %>
  password: <%= ENV.fetch("RAGDOLL_PASSWORD", "password") %>

production:
  <<: *default
  host: <%= ENV.fetch("RAGDOLL_HOST") %>
  database: <%= ENV.fetch("RAGDOLL_DATABASE") %>
  username: <%= ENV.fetch("RAGDOLL_USER") %>
  password: <%= ENV.fetch("RAGDOLL_PASSWORD") %>
